### ISSUE TITLE
Ajax 500 error

### ISSUE THREAD

**Issue by br-designer** [pixelandtonic/GuestEntries#16]
I'm getting a 500 server error when submitting the guest entries form via Ajax. The entries are saving in Craft regardless of the error, but I'm not getting a response back. This is using v1.5.2.

<img width="664" alt="screen shot 2016-11-23 at 11 04 41 am" src="https://cloud.githubusercontent.com/assets/5600724/20571507/4f11111e-b16d-11e6-9dc7-092181d37477.png">

```
<script src="/jquery.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                $("#form").submit(function(ev) {
                    ev.preventDefault();
                    var data = $(this).serialize();

                    $.ajax({
                        method: 'POST',
                        url: "/",
                        data: data,
                        headers: {'Content-Type': 'application/x-www-form-urlencoded'}
                    })
                    .success(function(data) {
                        console.log('success', data);
                    })
                    .error(function(data){
                        console.log('error', data);
                    });
                });
            });
        </script>
        <form id="form" method="post" action="" accept-charset="UTF-8">
            {{ getCsrfInput() }}
            <input type="hidden" name="action" value="guestEntries/saveEntry">
            <input type="hidden" name="redirect" value="/">
            <input type="hidden" name="sectionId" value="3">

            <label for="title">Title</label>
            <input id="title" type="text" name="title">

            <label for="title">Body</label>
            <input id="title" type="text" name="fields[body]">

    <input type="submit" value="Publish">
</form>
```
When I reverted back to v1.5.1, the guest entries works as expected.

**Comment by takobell** [comment]
Can you check `craft/storage/runtime/logs` for the underlying 500 Internal Server Error message?

**Comment by br-designer** [comment]
```
2016/11/23 19:24:19 [error] [exception.CException] exception 'CException' with message 'Property "Craft\EntryModel.getUrl" is not defined.' in /Users/kylebaker/Documents/Repositories/test/craft/app/framework/base/CComponent.php:130
Stack trace:
#0 /Users/kylebaker/Documents/Repositories/test/craft/app/models/BaseModel.php(87): CComponent->__get('getUrl')
#1 /Users/kylebaker/Documents/Repositories/test/craft/app/models/BaseElementModel.php(141): Craft\BaseModel->__get('getUrl')
#2 /Users/kylebaker/Documents/Repositories/test/craft/plugins/guestentries/controllers/GuestEntriesController.php(119): Craft\BaseElementModel->__get('getUrl')
#3 /Users/kylebaker/Documents/Repositories/test/craft/plugins/guestentries/controllers/GuestEntriesController.php(75): Craft\GuestEntriesController->_returnSuccess(Object(Craft\EntryModel))
#4 /Users/kylebaker/Documents/Repositories/test/craft/app/framework/web/actions/CInlineAction.php(49): Craft\GuestEntriesController->actionSaveEntry()
#5 /Users/kylebaker/Documents/Repositories/test/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /Users/kylebaker/Documents/Repositories/test/craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /Users/kylebaker/Documents/Repositories/test/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Users/kylebaker/Documents/Repositories/test/craft/app/framework/web/CWebApplication.php(282): CController->run('saveEntry')
#9 /Users/kylebaker/Documents/Repositories/test/craft/app/etc/web/WebApp.php(817): CWebApplication->runController('guestEntries/sa...')
#10 /Users/kylebaker/Documents/Repositories/test/craft/app/etc/web/WebApp.php(287): Craft\WebApp->_processActionRequest()
#11 /Users/kylebaker/Documents/Repositories/test/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#12 /Users/kylebaker/Documents/Repositories/test/craft/app/index.php(62): CApplication->run()
#13 /Users/kylebaker/Documents/Repositories/test/public_html/index.php(19): require_once('/Users/kylebake...')
#14 {main}
REQUEST_URI=/
HTTP_REFERER=http://dev2.test.dev/
---
2016/11/23 19:24:19 [trace] [system.CModule] Loading "errorHandler" application component
in /Users/kylebaker/Documents/Repositories/test/craft/app/etc/web/WebApp.php (595)
```

**Comment by br-designer** [comment]
Looks like updating line 119-121 of GuestEntriesController.php fixes the issue. 

```
if($entry->getUrl()){
    $return['url']	    = $entry->getUrl();
}
```

I'll do a pull request for this.
